### ISSUE TITLE
Smartling Connector Error Thrown

### ISSUE THREAD

**Issue by SMstevesf** [Smartling/wordpress-localization-plugin#149]
We are seeing this error every time the Smartling Cron is running.

> Error message Smartling\Exception\SmartlingDbException: Uncaught exception 'Smartling\Exception\SmartlingDbException' with message 'Error while deleting element from queue: ' in /wp-content/plugins/smartling-connector/inc/Smartling/Queue/Queue.php:151

While it does look like this is a normal exception being thrown, it would be good to know why the connector is having issues deleting an element and what element it can't delete.

**Comment by dimitrystd** [comment]
Personally i didn't see such error, so thx for report. We changed a little bit validation of query results and added query sql text to log in case of exception. So we will have much more information if it will happen again.

Can you check that queue table is empty?
```sql
SELECT COUNT(*)
FROM wp_smartling_queue;
```
I want to double check another potential case when data in queue table is not fully purged and something stuck here. If it's not empty, can you dump it for me. It can contain data for check status, which is not a problem.

**Comment by SMstevesf** [comment]
Sending you a dump through email now.

**Comment by paveldhq** [comment]
@SMstevesf, do you still experience the issue?

**Comment by SMstevesf** [comment]
@paveldhq Unfortunately we are. At this time, we are unable to move forward again due to the issues @ryanboswell submitted, the biggest being the file system write permissions. Once those are handled, we can walk through the upgrade process again.
