### ISSUE TITLE
Post Meta Being Duplicated

### ISSUE THREAD

**Issue by SMstevesf** [Smartling/wordpress-localization-plugin#150]
Hello, 

We are noticing that post meta fields are being duplicated when strings are being sent back after translation. In all cases these fields being added are blank, but causing errors. This is a little concerning as this means we need to clean up the database directly in order to fix this before we can promote and publish our content.

**Comment by dimitrystd** [comment]
JFYI, we are working on it.

**Comment by paveldhq** [comment]
Hello @SMstevesf,
After testing latest version we found that described bug cannot be reproduced.

Please provide us with next additional information:
- Which method was used to download translation (widget or cron job)?
- What is the file name (xml file name) of translation with issues?
- Please send us rows or post_meta tables with source metadata and translation
- Please send us log file that should contain download of translation with described issue.

Thanks.

**Comment by SMstevesf** [comment]
@paveldhq @dimitrystd following up in separate email thread. Laura was kind enough to grab a video of the issue. Will also follow with postmeta table from the site in the video.

**Comment by paveldhq** [comment]
Fixed in 3bba135

**Comment by paveldhq** [comment]
issue happens up to v. 1.5.1 if metadata value is a serialized array with one element.
