### ISSUE TITLE
Issues with deprecated post types

### ISSUE THREAD

**Issue by ryanboswell** [Smartling/wordpress-localization-plugin#154]
Updated to the 1.5.0 plugin and used the custom post type registration filters, but we've recently removed a post type we had before (and had Smartling submissions for). Loading the Settings screen complains about the post type not being valid and throws a Fatal error:

`
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid content type. Got 'partner', expected one of: post,page,attachment,post_tag,category,theme_widget,nav_menu_item,nav_menu,policy,testimonial' in /var/www/html/wordpress/wp-content/plugins/smartling-connector/inc/Smartling/Submissions/SubmissionEntity.php on line 448
`

Deleting all records in the `wp_smartling_submissions` with the `content_type` of `partner` seems to have fixed the issue, but that's not a very user-friendly approach. It'd be great if Smartling could either do it's own cleanup when post types are removed from WordPress (or a post itself is deleted), or at the very least not throw a fatal error and prevent plugin usage when it comes across a post type that doesn't exist or isn't registered with Smartling anymore.

**Comment by paveldhq** [comment]
Hello @ryanboswell, as you know content types are registered on every execution of wordpress. And there is no way to detect what is unregistered completely (and is not turned off for 10 minutes).
In case if you was using a custom post type and was translating it and then decided to cut it off from your project you should clean `wp_smartling_submissions` table from any submission of removed content type manually.

When the translation is removed smartling-connector catches and uses the hook to detect deletion and automatically removes the submission. In case if you remove the original content smartling-connector removes all related submissions and removes uploaded file. Note that moving to trash is not the deletion.

**Comment by ryanboswell** [comment]
I definitely understand that, and thinking about it more, automatically detecting content type changes isn't a great solution as you point out.

But it would still be great if a Fatal Error wasn't thrown if an unrecognized content type appears in the table. That prevents usage until someone can go into the database and clean it up (assuming a random user could figure that out to begin with, this is not a documented issue outside of this conversation), a better solution would be to recognize that and provide a user-friendly message about the rogue content type and either instructing the user to clean up the table themselves, or provide a UI tool that does it within the plugin.

Showing runtime errors to the user isn't a great experience at any level, for any reason, especially customers that have been using your plugin and service for some time and have out-dated database records. A database migration tool/process is common best practice to provide users the ability to keep their records clean and avoid issues as content and code evolves.

**Comment by paveldhq** [comment]
A new version released v. 1.5.1 that has issue fixed.
