### ISSUE TITLE
PHP Notice on dashboard widget

### ISSUE THREAD

**Issue by ryanboswell** [Smartling/wordpress-localization-plugin#155]
After updating to 1.5.0 I get a PHP Notice on my dashboard page in the core Quick Draft widget:

`Notice: Undefined index: post_type in /var/www/html/wordpress/wp-content/plugins/smartling-connector/inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php on line 267`

It looks like the code is looking for `$_POST['post_type']`, but is being run on a page that wasn't submitted to (request from browser was GET). Probably best to make sure the variable even exists before trying to compare against it.

**Comment by paveldhq** [comment]
A new version released v. 1.5.1 that has issue fixed.
