### ISSUE TITLE
File-system access issue

### ISSUE THREAD

**Issue by ryanboswell** [Smartling/wordpress-localization-plugin#156]
With the 1.5.0 update, the addition of `file_put_contents` in the [`plugins_loaded` action](https://github.com/Smartling/wordpress-localization-plugin/commit/5fe5b64767913aebbd82b7dfca9a1b46509a9425#diff-d11bc535f05a80a2d2af45932a3adaedR28) is causing a problem for us because our systems do not allow PHP to write to files, and warnings are being thrown on every page of the WP Admin.

What's the purpose of that file in a production-ready plugin? I don't see any purpose for what it does, and there's nothing else in the plugin that references the file you're creating.

**Comment by paveldhq** [comment]
Hello @ryanboswell,

smartling-connector needs to have writ access to its folder, since it writes logs into files. Also smartoing-connector plugin is trying to create a recovery file that helps in case that smartling-connector plugin or any its extension fails and breaks wordpress functionality.

I highly recommend you allow write access for smartling-connector to its folder (and also to /uploads folder too if it isn't so).

**Comment by ryanboswell** [comment]
The self-recovery approach is definitely interesting, but this is the first time I've seen a plugin do that, so I'm not sure it follows best practices. There are [countless articles](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=recovering+from+broken+plugin+wordpress&*) on the internet explaining how to recover from a broken plugin in WordPress without resorting to a custom-built file to do so.

As a [general rule](https://codex.wordpress.org/Hardening_WordPress#File_Permissions), only `wp-content/uploads` is supposed to be writeable for security reasons, and even if some hosts default to allowing system commands write access outside of that scope, the vast majority of enterprise customers (and all of WordPress VIP) won't. WordPress' official guidelines recommend users prevent direct `.php` file execution outside of core files, which would render the `recovery.php` file useless.

It's understandable to want to allow users an easy recovery option, even though it's mostly unnecessary. But if you're sure, it should be simple enough to ensure that advanced users with stricter security requirements are able to use your product without major problems by checking if the required directory is [writeable](http://php.net/manual/en/function.is-writable.php) before proceeding, and moving on gracefully if not rather than throwing a fatal error or warning. At the most severe, I could see a dismissible notice to admin users in the WP Admin area recommending they allow write access to the plugin folder being reasonable.

**Comment by paveldhq** [comment]
removed recovery script generation code.
