### ISSUE TITLE
Allow self-update checks to be disabled

### ISSUE THREAD

**Issue by ryanboswell** [Smartling/wordpress-localization-plugin#158]
With the 1.5.8 release, I noticed that the plugin now performs it's own update checks, independent of WordPress core. Normally I wouldn't have a problem with that, but in some enterprise environments (like one I work with), version management is done manually and these update prompts only get in the way of normal usage while reviews are done on code updates.

WordPress core does all it's update checks on action hooks which can be deregistered by advanced users, it'd be nice to see a similar approach done in the Smartling plugin.

**Comment by paveldhq** [comment]
Independent update checks are removed.
Self-version checks are optional (Settings screen)
