### ISSUE TITLE
Self-update network calls are too frequent

### ISSUE THREAD

**Issue by ryanboswell** [Smartling/wordpress-localization-plugin#159]
In the 1.5.8 update, the fully independent version update checks are potentially performed on every page load in instances where WordPress core update checks are disabled and thus the cached data is not available. This presents quite the problem in security-aware and performance-turned environments where external network access is disabled or tightly controlled and monitored.

WordPress core caches the data from each check and also prevents checks from occurring too frequently, for plugins the default is once per hour to ensure that WordPress users do not see a performance hit and so that the Update API does not get overloaded by hundreds or thousands of simultaneous requests from a single high-traffic site.

Ideally these independent checks aren't necessary since WordPress performs it's own checks and prompts to users, but if it's important, simply calling WordPress' own [core update check function](https://developer.wordpress.org/reference/functions/wp_version_check/) should suffice, and will allow for rate limiting and caching to ensure high performance and efficiency.

I'll also point out that it is considered best practice to perform operations like this only on Admin context requests and avoid making them on front-end (ie. the end-user portion of the site) requests. That helps ensure better security and end-user performance.

**Comment by paveldhq** [comment]
Self-update network calls are removed from the code
