### ISSUE TITLE
Operational messages should only appear to admins

### ISSUE THREAD

**Issue by ryanboswell** [Smartling/wordpress-localization-plugin#160]
In the 1.5.8 update, I noticed that the prompt for updating the plugin is displayed to all users, regardless of their role on the site. While this isn't terrible, it's usually best practice to display those kinds of notices to site or network admins only (WordPress core does this), since most users won't be able to do anything about an out-of-date plugin.

And in some rare cases such information being freely available to any user can present a security risk (ie. a commenter that can freely register an account and is able to see the Admin dashboard to edit their profile) if there is a known vulnerability in an older version of a plugin.

**Comment by paveldhq** [comment]
Cron setup information is appears only to users with **manage_network_plugins** ability
