### ISSUE TITLE
Allow for alternative cron setups in wp-cron check

### ISSUE THREAD

**Issue by ryanboswell** [Smartling/wordpress-localization-plugin#161]
In the latest 1.5.8 release I see that you added a self-test to ensure that wp-cron is not disabled. While cron may be important to Smartling's operations, there are multiple ways in which WP Cron can be run through alternative setups, which are quite common in large, distributed and high-traffic WordPress environments where the default WP Cron implementation is fragile and inconsistent. Almost all of those alternatives require that the `DISABLE_WP_CRON` flag is set to ensure there aren't any conflicts, which would result in the diagnostic message warning about cron setup to be permanently displayed on a user's WordPress install.

There are [numerous](https://wpengine.com/support/wp-cron-wordpress-scheduling/) [articles](https://tribulant.com/blog/wordpress/replace-wordpress-cron-with-real-cron-for-site-speed/) [on the web](https://developer.wordpress.org/cli/commands/cron/) that describe alternative setups for running WP Cron jobs.

That kind of message should be permanently dismissible so that advanced users are able to configure environments to their needs and not be prompted about a non-issue, and/or there should be a more robust and forgiving check that takes into account a wide range of ways in which cron can be setup to run.

**Comment by paveldhq** [comment]
self-check can be disabled through Settings screen
