### ISSUE TITLE
Confusing Download button 'title' attribute

### ISSUE THREAD

**Issue by ryanboswell** [Smartling/wordpress-localization-plugin#165]
It appears that the Download button's [title attribute](https://github.com/Smartling/wordpress-localization-plugin/blob/e01d1d95b8a547f732cf4d65c9a9b51f75ab871d/inc/Smartling/WP/WPAbstract.php#L241) is copied from the Upload button, and it's a bit confusing seeing it in the interface.

**Comment by dimitrystd** [comment]
Thanks, fixed.
