### ISSUE TITLE
Test if $role is not NULL

### ISSUE THREAD

**Issue by pavelescurazvan** [Smartling/wordpress-localization-plugin#167]
https://github.com/Smartling/wordpress-localization-plugin/blob/41cc5cc079ab857dbb70b96e64b84b9a7fa23633/inc/Smartling/Bootstrap.php#L194

There are cases when get_role('administrator'); returns NULL.

Please test before calling the add_cap method that $role is not NULL.

**Comment by paveldhq** [comment]
fixed
