### ISSUE TITLE
ACF plugin check is intensive

### ISSUE THREAD

**Issue by ryanboswell** [Smartling/wordpress-localization-plugin#169]
While looking at the latest version running on our test environments, we noticed a rather enormous amount of debug logging dedicated to checking whether or not the ACF plugin is present and active, on what looks to be every single page load (and possibly more than once on a page, but I haven't been able to really determine that).

Either way, it looks like there's quite a lot of overhead trying to always check if the plugin exists, so I'd recommend using a WordPress action that only the ACF plugin itself fires, like the [`acf/init`](https://www.advancedcustomfields.com/resources/acf-init/) action. That should give you absolute certainty that you can run whatever code you need to if and only if the plugin is active, and it'll be sure to only run once per page.

**Comment by paveldhq** [comment]
Hello @ryanboswell,

Smartling-connector is looking for registered content types of ACF plugin once per load. It is required to build special filters to process post metadata fields created by ACF plugin.

Usage of `acf/init` is not currently possible because it requires ACF v.5 (paid version), but there are users with a free version of ACF plugin (v.4) that doesn't have such ability.

Thanks, Pavlo.

**Comment by ryanboswell** [comment]
@paveldhq in that case, I'd expect the setting to disable ACF lookups to also apply to checking for the ACF plugin at all, or maybe a second option to take that step. For those of us that do not use ACF, it'd be nice to skip that overhead for performance reasons (and to keep our logs from cluttering with debug information we don't need).

**Comment by dimitrystd** [comment]
A little bit background about ACF.
Before ACF was the standalone plugin https://github.com/Smartling/wordpress-acf-localization-plugin. And it was the right solution but it didn't take into account human factor. No one reads documentation and pretty lazy to do some additional steps. ACF is very popular and under pressure of a number of support tickets, we decided to add ACF into core plugin.

We understand your concern. Noise in logs and additional CPU usage should not affect those who don't use ACF. So we will consider adding "disable ACF" option.
